# Generated by Django 4.1.3 on 2023-01-27 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActiveBlogManager',
        ),
    ]
